Review welcome
innoq/microservice-consul pull request #1
Opened 2017-01-19 20:47 UTC by aheusingfeld

Updated the demo after feedback in today's training. Please check the comments on the different commits below for details.

2017-01-20 08:03 UTC, mvitz requested changes
At least the subtle bug in the README regarding the _ must be resolved before merging this.

2017-01-20 08:03 UTC, mvitz commented on README.md
> +Note that the demo uses the original []Consul Docker template](https://hub.docker.com/_/consul/) provided
The _ used in the URI leads to italic text afterwards. Because of that the _ must be escaped.

2017-01-20 08:03 UTC, mvitz commented on microservice-consul-demo/microservice-consul-demo-catalog/pom.xml
> +			<groupId>org.springframework.boot</groupId>
Maybe that is pedantic but I prefer adding the optional spring-boot devtools to the end of the dependencies list.

2017-01-20 08:03 UTC, mvitz commented on microservice-consul-demo/microservice-consul-demo-catalog/src/main/resources/templates/layout.html
> +				<li><a class="brand" href="https://github.com/ultraq/thymeleaf-layout-dialect">Thymeleaf - Layout</a></li>
Can this link be removed completely? At least I never used it.

2017-01-20 08:03 UTC, mvitz commented on microservice-consul-demo/microservice-consul-demo-order/src/test/java/com/ewolff/microservice/order/logic/CustomerConsumerDrivenContractTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT, classes = OrderApp.class)
I personally prefer the `RANDOM_PORT` but for the sake of this example `DEFINED_PORT` may be good enough.

2017-01-20 08:03 UTC, mvitz commented on microservice-consul-demo/microservice-consul-demo-order/src/test/java/com/ewolff/microservice/order/logic/OrderWebIntegrationTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT, classes = OrderApp.class)
See https://github.com/innoq/microservice-consul/pull/1/files#r97026524

2017-01-20 08:03 UTC, mvitz commented on microservice-consul-demo/microservice-consul-demo-order/src/test/java/com/ewolff/microservice/order/logic/CatalogConsumerDrivenContractTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT, classes = OrderApp.class)
See https://github.com/innoq/microservice-consul/pull/1/files#r97026524

2017-01-21 12:23 UTC, aheusingfeld commented
@mvitz it's actually been a broken link! Well spotted, thanks a lot. Should be fixed now

2017-01-21 16:19 UTC, mvitz commented
I guess you do not agree with the additional comments and want this to be merged as is?

2017-01-21 19:47 UTC, aheusingfeld commented on microservice-consul-demo/microservice-consul-demo-catalog/pom.xml
> +			<groupId>org.springframework.boot</groupId>
I have no preference. What's your reasoning behind?

2017-01-21 19:48 UTC, aheusingfeld commented on microservice-consul-demo/microservice-consul-demo-catalog/src/main/resources/templates/layout.html
> +				<li><a class="brand" href="https://github.com/ultraq/thymeleaf-layout-dialect">Thymeleaf - Layout</a></li>
That's a question for @ewolff. As this is a public sample, he might have had a reason adding it in the first place

2017-01-21 19:51 UTC, aheusingfeld commented on microservice-consul-demo/microservice-consul-demo-order/src/test/java/com/ewolff/microservice/order/logic/CustomerConsumerDrivenContractTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT, classes = OrderApp.class)
I didn't invest the time to check the backgrounds but with RANDOM_PORT the CDC tests failed. I'd suggest to open a ticket for that. Agree?

2017-01-22 09:05 UTC, ewolff commented on microservice-consul-demo/microservice-consul-demo-catalog/src/main/resources/templates/layout.html
> +				<li><a class="brand" href="https://github.com/ultraq/thymeleaf-layout-dialect">Thymeleaf - Layout</a></li>
It's just a copy from some sample. I'll remove it.

2017-01-22 09:06 UTC, ewolff commented on microservice-consul-demo/microservice-consul-demo-catalog/pom.xml
> +			<groupId>org.springframework.boot</groupId>
I guess I agree with @mvitz

2017-01-22 09:11 UTC, ewolff commented on microservice-consul-demo/microservice-consul-demo-order/src/test/java/com/ewolff/microservice/order/logic/CustomerConsumerDrivenContractTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT, classes = OrderApp.class)
The tests use the `RestTemplate` to access the services. I suspect they have a hard coded port. Opening a ticket seems a good idea.

2017-01-22 09:13 UTC, ewolff approved these changes
Thanks for the changes and review!

2017-01-22 09:13 UTC, ewolff commented
Thanks!

2017-01-22 09:13 UTC, merged